-- Run this once in Supabase SQL Editor before testing the API.

create table if not exists public.contacts (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  message text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  service text not null,
  date text not null,
  time text,
  message text,
  status text not null default 'pending',
  created_at timestamptz not null default now(),
  constraint bookings_status_check check (status in ('pending', 'confirmed', 'declined', 'completed'))
);

create index if not exists contacts_created_at_idx on public.contacts (created_at desc);
create index if not exists bookings_created_at_idx on public.bookings (created_at desc);
create index if not exists bookings_date_idx on public.bookings (date);

-- The API uses the Supabase service-role key server-side, so these tables do not
-- need public INSERT/SELECT policies for the website's API routes.
-- Keep the service-role key out of frontend code and browser-exposed variables.
